[project]
name = "rag_code_chat"
version = "0.1.0"
description = "GitHub Repo Code explorer using RAG"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit",
    "python-dotenv",
    "llama-index-llms-gemini",
    "llama-index-embeddings-gemini",
    "google-genai",
    "llama-index-readers-github",
    "llama-index",
    "nest-asyncio"
]
